#!/usr/bin/env python3
"""`./init --extension sonar`: configure an on-demand Sonar scan and point the agent at it.

Sonar is remote, credentialed analysis. It complements the native, deterministic `make verify` gate; it
does not replace or join it. Configuration is committed, while the host and token remain in the
environment. Missing optional tooling is reported without failing `./init`.
"""
from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

sys.dont_write_bytecode = True
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from guidance import record_extension, replace_block  # noqa: E402


def project_root(script: Path, depth: int) -> Path:
    """Find the repository root without assuming where delivery tooling was installed."""
    for candidate in script.parents:
        if (candidate / "project.json").is_file():
            return candidate
    return script.parents[depth]


ROOT = project_root(Path(__file__).resolve(), 3)
MANIFEST = ROOT / "project.json"
PROPERTIES = ROOT / "sonar-project.properties"
MARKER_BEGIN = "<!-- extension:sonar:begin -->"
MARKER_END = "<!-- extension:sonar:end -->"
GUIDANCE = f"""
{MARKER_BEGIN}
## Sonar
This project can publish an on-demand analysis to SonarQube or SonarCloud with `make sonar`. Sonar is a
remote dashboard and coverage sink; `make verify` and its native lint, typecheck and test tools remain the
merge gate. The Sonar target reruns tests to produce its own coverage reports, outside that gate.

Before relying on Sonar, check that this environment has `SONAR_HOST_URL` and `SONAR_TOKEN`, plus
`sonar-scanner` for TypeScript, Python or Go projects. Java projects use their Maven wrapper. A checkout
does not carry those credentials or tools with it. If either is unavailable, say that the remote analysis
was not consulted and continue from the local gate. Never print, commit or pass the token on a command
line; the scanners read it from the environment.
{MARKER_END}
"""


def project_guidance() -> None:
    """Record this election and make its factory-owned guidance region current."""
    record_extension("sonar")
    replace_block("sonar", GUIDANCE)


def properties(document: dict) -> str:
    """Stable, non-secret scanner identity derived from the project manifest."""
    name = document["name"]
    return (
        "# Generated by ./init --extension sonar; credentials stay in the environment.\n"
        f"sonar.projectKey={name}\n"
        f"sonar.projectName={name}\n"
        "sonar.sourceEncoding=UTF-8\n"
    )


def needs_standalone_scanner(document: dict) -> bool:
    """Java-only repositories use Maven; every other shape needs the standalone scanner."""
    deployables = document.get("deployables", {}).values()
    return any(
        app.get("kind") != "service" or app.get("language") != "java"
        for app in deployables
    )


def main() -> int:
    document = json.loads(MANIFEST.read_text())
    if needs_standalone_scanner(document) and shutil.which("sonar-scanner") is None:
        print(
            "Sonar Scanner CLI not found: sonar-project.properties and AGENTS.md are unchanged.\n"
            "Install sonar-scanner from https://docs.sonarsource.com/sonarqube-server/analyzing-source-code/"
            "scanners/sonarscanner/ and then adopt it here:\n"
            "  ./init --extension sonar",
            file=sys.stderr,
        )
        return 0
    PROPERTIES.write_text(properties(document))
    project_guidance()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
