#!/usr/bin/env python3
"""`./init --extension sonar`: configure an on-demand Sonar scan and point the agent at it.

Sonar is remote, credentialed analysis. It complements the native, deterministic `make verify` gate; it
does not replace or join it. Configuration is committed, while the host and token remain in the
environment. Missing optional tooling is reported without failing `./init`.

`sonar-project.properties` is **merged, never rewritten**. The generated file cannot be complete — SonarCloud
requires `sonar.organization` and `project.json` holds no organisation — so the user finishes it by hand, and
a rerun that threw that edit away would be a silent data loss in a file nothing else reads back. This rewrites
only the keys it owns and keeps every other line as it was.
"""
from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

sys.dont_write_bytecode = True
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from guidance import record_extension, replace_block  # noqa: E402


def project_root(script: Path, depth: int) -> Path:
    """Find the repository root without assuming where delivery tooling was installed."""
    for candidate in script.parents:
        if (candidate / "project.json").is_file():
            return candidate
    return script.parents[depth]


ROOT = project_root(Path(__file__).resolve(), 3)
MANIFEST = ROOT / "project.json"
PROPERTIES = ROOT / "sonar-project.properties"
MARKER_BEGIN = "<!-- extension:sonar:begin -->"
MARKER_END = "<!-- extension:sonar:end -->"
GUIDANCE = f"""
{MARKER_BEGIN}
## Sonar
This project can publish an on-demand analysis to SonarQube or SonarCloud with `make sonar`. Sonar is a
remote dashboard and coverage sink; `make verify` and its native lint, typecheck and test tools remain the
merge gate. The Sonar target reruns tests to produce its own coverage reports, outside that gate.

Before relying on Sonar, check that this environment has `SONAR_HOST_URL` and `SONAR_TOKEN`, plus
`sonar-scanner` for TypeScript, Python or Go projects. Java projects use their Maven wrapper. A checkout
does not carry those credentials or tools with it. If either is unavailable, say that the remote analysis
was not consulted and continue from the local gate. Never print, commit or pass the token on a command
line; the scanners read it from the environment.
{MARKER_END}
"""


def project_guidance() -> None:
    """Record this election and make its factory-owned guidance region current."""
    record_extension("sonar")
    replace_block("sonar", GUIDANCE)


# The keys this extension derives from `project.json` and therefore owns. Everything else in the file belongs
# to whoever wrote it — `sonar.organization`, which SonarCloud requires and no manifest field can supply;
# exclusions; coverage paths — and is kept verbatim on every rerun. The generated file is by construction
# incomplete for the SonarCloud case, so it is a file the user must hand-edit, which makes it a merge target
# and never a write target (`docs/extensions.md`, *What `init.py` owes*, item 6). Written unconditionally, this
# deleted a hand-added organisation on every `./init` that reached the extension — silently, only where the
# scanner happened to be installed, and surfacing later as an analysis filed against nothing.
OWNED = ("sonar.projectKey", "sonar.projectName", "sonar.sourceEncoding")
HEADER = "# Generated by ./init --extension sonar; credentials stay in the environment."
KEPT = "# Lines below this one are yours: this file is merged on rerun, never rewritten."


def owned(document: dict) -> dict[str, str]:
    """The keys this extension derives, in the order it writes them."""
    name = document["name"]
    return {"sonar.projectKey": name, "sonar.projectName": name, "sonar.sourceEncoding": "UTF-8"}


def merged(document: dict, existing: str | None) -> str:
    """The generated keys, then every line of an existing file this extension does not own, as it was.

    A line is "not ours" unless its key is in `OWNED`; a comment, a blank line and a key nobody here knows are
    all kept. The two comments this extension writes are dropped from the kept side so a rerun does not stack
    copies of them.
    """
    lines = [HEADER] + [f"{key}={value}" for key, value in owned(document).items()]
    theirs = [
        line for line in (existing or "").splitlines()
        if line.split("=", 1)[0].strip() not in OWNED and line.strip() not in (HEADER, KEPT)
    ]
    while theirs and not theirs[0].strip():
        theirs.pop(0)
    while theirs and not theirs[-1].strip():
        theirs.pop()
    if theirs:
        lines += ["", KEPT, *theirs]
    return "\n".join(lines) + "\n"


def needs_standalone_scanner(document: dict) -> bool:
    """Java-only repositories use Maven; every other shape needs the standalone scanner."""
    deployables = document.get("deployables", {}).values()
    return any(
        app.get("kind") != "service" or app.get("language") != "java"
        for app in deployables
    )


def main() -> int:
    document = json.loads(MANIFEST.read_text())
    if needs_standalone_scanner(document) and shutil.which("sonar-scanner") is None:
        print(
            "Sonar Scanner CLI not found: sonar-project.properties and AGENTS.md are unchanged.\n"
            "Install sonar-scanner from https://docs.sonarsource.com/sonarqube-server/analyzing-source-code/"
            "scanners/sonarscanner/ and then adopt it here:\n"
            "  ./init --extension sonar",
            file=sys.stderr,
        )
        return 0
    PROPERTIES.write_text(merged(document, PROPERTIES.read_text() if PROPERTIES.is_file() else None))
    project_guidance()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
